env:
  repo:
    github_url: https://github.com/SWE-agent/test-repo
  deployment:
    # type: "modal" # modal, docker
    image: "python:3.12"
  post_startup_commands: [
      "curl -LsSf https://astral.sh/uv/install.sh | sh", # install uv
      "curl -LsSf https://astral.sh/ruff/install.sh | sh", # install ruff
      "pip install pytest", # install pytest
    ]
